remote_theme: zivhub/monophase
#remote_theme: pages-themes/primer
#remote_theme: eecs485staff/primer-spec
title: Curso de Astronomía 2021
#description: A short description of your site's purpose
#name: Ernesto Nicola
#github:
#  private: true
